### ISSUE TITLE
ElytronCallerDetailsResolver.getPrincipalsByType does not include subtypes

### ISSUE THREAD

**Issue by roeltje25** [wildfly-security/wildfly-elytron-ee#25]
Hi,

There is a bug in ElytronCallerDetailsResolver on line 47. Because the isAssignableFrom call is inverted subtypes are not considered as valid principals. This is wrong I think. For example, we have AppUsers and AppAdminUsers as principals and in fact AppAdminUsers are also AppUsers. However the resolver will discard any AppAdminUsers requested by getPrincipalsByType(AppUser.class). 

Could you fix this? In fact it makes wildfly 28 break all our apps.

regards,

Roel

**Comment by fjuma** [comment]
Hi @roeltje25,

Would you be able to create a bug report for this here:
https://issues.redhat.com/projects/ELYEE

Thanks very much,
Farah

**Comment by darranl** [comment]
Closing as moved to Jira
