### ISSUE TITLE
The `PolicyUtil` should clear the `ThreadLocal` if the passed in policy is null

### ISSUE THREAD

**Issue by jamezp** [wildfly-security/wildfly-elytron-ee#47]
In the new `PolicyUtil` to help with the removal of the security manager functionality in Java 24+, a `ThreadLocal` is used to store a `java.security.Policy`. When a `null` policy is passed it, the value is still set on the `ThreadLocal`. It should remove the `ThreadLocal` value instead of setting it to `null`. This clears the `ThreadLocal` from the internal map.

**Comment by darranl** [comment]
Closing as we use the following Jira project for issues https://issues.redhat.com/browse/ELYEE
